### PR TITLE
Starter Kit for Telegram Mini App for EVM compatible chains

### PR DESCRIPTION
**Pull request by HAPPYS1NGH**
Added Starter Kit with
 - NextJS
 - Typescript
 - WAGMI
 - RainbowKit
 - Tailwind CSS
 - ShadCN
 - LocalTunnel
 - Telegram SDK

### CODE REVIEW

**Comment by panditdhamdhere** [comment]
hi @HAPPYS1NGH Thank you very much for really great PR, can you please update contributions.md with your name.

**Review by panditdhamdhere — COMMENTED** [review]
Really great pull request man, please update contributions.md

**Comment by HAPPYS1NGH** [comment]
@panditdhamdhere Updated Contributions.md

Let me know if you want something else.

**Review by panditdhamdhere — APPROVED** [review]
great job ser! thank you very much again for great PR

**Pull request merged**
