### PR TITLE
GraphQL implementation

### PR DESCRIPTION
**Pull request by SIDHARTH20K4**
Created a simple dApp 
Queried with the help of graphQL

### CODE REVIEW

**Review by panditdhamdhere — CHANGES_REQUESTED** [review]
In your contract you written license multiple times! correct this

**Comment by SIDHARTH20K4** [comment]
@panditdhamdhere 
Sure!! will do it

**Comment by panditdhamdhere** [comment]
it will be even better if you can add ReadME with how to use this

**Review by panditdhamdhere — APPROVED** [review]

**Comment by SIDHARTH20K4** [comment]
Sure!!

**Pull request merged**
